# Generated by ./configure script - Tue Oct  1 23:31:26 UTC 2019
# Modifications to this file are lost if ./configure is ran again.

CONF_VERSION = 1.0.5
CONF_CFLAGS = -Wall -O2 -g
CONF_ASN_CFLAGS = 
CONF_PREFIX = /usr/local
CONF_PRECOMPILED_ASN = yes
CONF_SUPL_DEBUG = 
CONF_ASN1_SKELETONS = 
