# Generated by ./configure script - Wed Oct  2 18:34:55 UTC 2019
# Modifications to this file are lost if ./configure is ran again.

CONF_VERSION = 1.0.5
CONF_CFLAGS = -Wall -O2 -g
CONF_ASN_CFLAGS = 
CONF_PREFIX = /usr/local
CONF_PRECOMPILED_ASN = 
CONF_SUPL_DEBUG = -DSUPL_DEBUG
CONF_ASN1_SKELETONS = 
